name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LibMan CLI
        run: dotnet tool install -g Microsoft.Web.LibraryManager.Cli

      - name: Restore client-side libraries with LibMan
        run: libman restore

      - name: Deploy source files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: 8.209.70.189
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /var/www/sofrani2paylas/
          security: loose

      - name: Execute build and run commands on server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 8.209.70.189
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/sofrani2paylas
            dotnet restore
            cd SoframiPaylas.WebAPI
            dotnet run
      - name: Execute build and run commands on server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 8.209.70.189
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/sofrani2paylas
            dotnet restore
            cd SoframiPaylas.WebUI
            dotnet run
